Дз 14 Docker 2
Otus-DevOps-2021-02/avoronovat_microservices pull request #1
Opened 2021-05-28 12:09 UTC by avoronovat

# Выполнено ДЗ № 14 (по лекции 16)

 - [+] Основное ДЗ
 - [+] Задание со *

## В процессе сделано:
 - установлен докер
 - прошел введение в образы
 - создал контейнер из образа
 - изучены основы
 - научился запускать новые контейнеры на локальной машине
 - научился создавать образы из контейнера
 - создал докер машину для запуска контейнеров в облаке яндекса
 - создал образ "нашего" приложения
 - зарегал на докер хабе и выложил свой образ
 - со * - инстанс на терраформом с переменной count, установка докера и приложения из образа с хаба

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-05-28 13:27 UTC, avoronovat commented
@mrgreyves Нид хэлп, все равно не могу понять почему ругается на автотест. И на установку монгодб-сервер если пытаешься забилдить тест образ на локальной машине.

2021-06-01 11:21 UTC, mrgreyves requested changes
Здравствуйте!) Тесты валятся на этапе билда образа, в тестах конкретно указана команда с которой проблема "+The command '/bin/sh -c cd /reddit && bundle install' returned a non-zero code: 1". Попробуйте собрать локально. Так же можно поставить версию ubuntu 16,04.

2021-06-01 14:57 UTC, avoronovat commented
> Здравствуйте!) Тесты валятся на этапе билда образа, в тестах конкретно указана команда с которой проблема "+The command '/bin/sh -c cd /reddit && bundle install' returned a non-zero code: 1". Попробуйте собрать локально. Так же можно поставить версию ubuntu 16,04.

да 16.04 помогло. Спасибо.

2021-06-03 08:44 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-06-03 14:53 UTC, merged